server:
  port: 8084
spring:
  application:
    name: job-worker

flowjob:
  worker:
    brokers:
      - http://localhost:8081
    taskQueueSize: 64
    tags:
      - a=b
      - c=d
    auto-register: true
